-- Drop all t3_better_auth_ prefixed tables
DROP TABLE IF EXISTS t3_better_auth_account CASCADE;
DROP TABLE IF EXISTS t3_better_auth_emi_plan CASCADE;
DROP TABLE IF EXISTS t3_better_auth_fee_application CASCADE;
DROP TABLE IF EXISTS t3_better_auth_fee_structure CASCADE;
DROP TABLE IF EXISTS t3_better_auth_installment CASCADE;
DROP TABLE IF EXISTS t3_better_auth_institution CASCADE;
DROP TABLE IF EXISTS t3_better_auth_institution_payment CASCADE;
DROP TABLE IF EXISTS t3_better_auth_invitation CASCADE;
DROP TABLE IF EXISTS t3_better_auth_location CASCADE;
DROP TABLE IF EXISTS t3_better_auth_member CASCADE;
DROP TABLE IF EXISTS t3_better_auth_organization CASCADE;
DROP TABLE IF EXISTS t3_better_auth_parent_profile CASCADE;
DROP TABLE IF EXISTS t3_better_auth_payment CASCADE;
DROP TABLE IF EXISTS t3_better_auth_post CASCADE;
DROP TABLE IF EXISTS t3_better_auth_session CASCADE;
DROP TABLE IF EXISTS t3_better_auth_student CASCADE;
DROP TABLE IF EXISTS t3_better_auth_user CASCADE;
DROP TABLE IF EXISTS t3_better_auth_verification CASCADE;
