CREATE TABLE IF NOT EXISTS "t3_better_auth_account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3_better_auth_emi_plan" (
	"id" text PRIMARY KEY NOT NULL,
	"fee_structure_id" text NOT NULL,
	"name" text NOT NULL,
	"installments" integer NOT NULL,
	"interest_rate" numeric(5, 2) DEFAULT '0.00',
	"processing_fee" numeric(10, 2) DEFAULT '0.00',
	"is_active" boolean DEFAULT true,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3_better_auth_fee_application" (
	"id" text PRIMARY KEY NOT NULL,
	"student_id" text NOT NULL,
	"fee_structure_id" text NOT NULL,
	"emi_plan_id" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"total_amount" numeric(10, 2) NOT NULL,
	"remaining_amount" numeric(10, 2) NOT NULL,
	"monthly_installment" numeric(10, 2),
	"applied_at" timestamp NOT NULL,
	"approved_at" timestamp,
	"approved_by" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3_better_auth_fee_structure" (
	"id" text PRIMARY KEY NOT NULL,
	"institution_id" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"amount" numeric(10, 2) NOT NULL,
	"due_date" timestamp,
	"academic_year" text NOT NULL,
	"semester" text,
	"is_recurring" boolean DEFAULT false,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3_better_auth_installment" (
	"id" text PRIMARY KEY NOT NULL,
	"fee_application_id" text NOT NULL,
	"installment_number" integer NOT NULL,
	"amount" numeric(10, 2) NOT NULL,
	"due_date" timestamp NOT NULL,
	"paid_date" timestamp,
	"status" text DEFAULT 'pending' NOT NULL,
	"payment_id" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3_better_auth_institution" (
	"id" text PRIMARY KEY NOT NULL,
	"organization_id" text NOT NULL,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"address" text,
	"phone" text,
	"email" text,
	"website" text,
	"logo" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3_better_auth_invitation" (
	"id" text PRIMARY KEY NOT NULL,
	"organization_id" text NOT NULL,
	"email" text NOT NULL,
	"role" text NOT NULL,
	"status" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"inviter_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3_better_auth_member" (
	"id" text PRIMARY KEY NOT NULL,
	"organization_id" text NOT NULL,
	"user_id" text NOT NULL,
	"role" text NOT NULL,
	"created_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3_better_auth_organization" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"slug" text,
	"logo" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp with time zone,
	"metadata" text,
	CONSTRAINT "t3_better_auth_organization_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3_better_auth_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3_better_auth_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3_better_auth_session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp with time zone,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	"impersonated_by" text,
	CONSTRAINT "t3_better_auth_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3_better_auth_student" (
	"id" text PRIMARY KEY NOT NULL,
	"parent_id" text NOT NULL,
	"institution_id" text NOT NULL,
	"name" text NOT NULL,
	"roll_number" text,
	"class" text,
	"section" text,
	"admission_date" timestamp,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3_better_auth_user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"is_premium" boolean DEFAULT false NOT NULL,
	"role" text,
	"banned" boolean,
	"ban_reason" text,
	"ban_expires" timestamp,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "t3_better_auth_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3_better_auth_verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_account" ADD CONSTRAINT "t3_better_auth_account_user_id_t3_better_auth_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."t3_better_auth_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_emi_plan" ADD CONSTRAINT "t3_better_auth_emi_plan_fee_structure_id_t3_better_auth_fee_structure_id_fk" FOREIGN KEY ("fee_structure_id") REFERENCES "public"."t3_better_auth_fee_structure"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_fee_application" ADD CONSTRAINT "t3_better_auth_fee_application_student_id_t3_better_auth_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."t3_better_auth_student"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_fee_application" ADD CONSTRAINT "t3_better_auth_fee_application_fee_structure_id_t3_better_auth_fee_structure_id_fk" FOREIGN KEY ("fee_structure_id") REFERENCES "public"."t3_better_auth_fee_structure"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_fee_application" ADD CONSTRAINT "t3_better_auth_fee_application_emi_plan_id_t3_better_auth_emi_plan_id_fk" FOREIGN KEY ("emi_plan_id") REFERENCES "public"."t3_better_auth_emi_plan"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_fee_application" ADD CONSTRAINT "t3_better_auth_fee_application_approved_by_t3_better_auth_user_id_fk" FOREIGN KEY ("approved_by") REFERENCES "public"."t3_better_auth_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_fee_structure" ADD CONSTRAINT "t3_better_auth_fee_structure_institution_id_t3_better_auth_institution_id_fk" FOREIGN KEY ("institution_id") REFERENCES "public"."t3_better_auth_institution"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_installment" ADD CONSTRAINT "t3_better_auth_installment_fee_application_id_t3_better_auth_fee_application_id_fk" FOREIGN KEY ("fee_application_id") REFERENCES "public"."t3_better_auth_fee_application"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_institution" ADD CONSTRAINT "t3_better_auth_institution_organization_id_t3_better_auth_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."t3_better_auth_organization"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_invitation" ADD CONSTRAINT "t3_better_auth_invitation_organization_id_t3_better_auth_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."t3_better_auth_organization"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_invitation" ADD CONSTRAINT "t3_better_auth_invitation_inviter_id_t3_better_auth_user_id_fk" FOREIGN KEY ("inviter_id") REFERENCES "public"."t3_better_auth_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_member" ADD CONSTRAINT "t3_better_auth_member_organization_id_t3_better_auth_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."t3_better_auth_organization"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_member" ADD CONSTRAINT "t3_better_auth_member_user_id_t3_better_auth_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."t3_better_auth_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_post" ADD CONSTRAINT "t3_better_auth_post_created_by_t3_better_auth_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."t3_better_auth_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_session" ADD CONSTRAINT "t3_better_auth_session_user_id_t3_better_auth_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."t3_better_auth_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_student" ADD CONSTRAINT "t3_better_auth_student_parent_id_t3_better_auth_user_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."t3_better_auth_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "t3_better_auth_student" ADD CONSTRAINT "t3_better_auth_student_institution_id_t3_better_auth_institution_id_fk" FOREIGN KEY ("institution_id") REFERENCES "public"."t3_better_auth_institution"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "created_by_idx" ON "t3_better_auth_post" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "name_idx" ON "t3_better_auth_post" USING btree ("name");